### ISSUE TITLE
Lj-inventory/server/main.lua:26 : attempt to index nil value (field 'items')

### ISSUE THREAD

**Issue by TheRealZenZo** [loljoshie/lj-inventory#103]
Getting this issue, and i think this issue may be why im not being able to fully load into the server 
<img width="731" alt="image" src="https://user-images.githubusercontent.com/65645201/203135515-7c676129-d41d-470c-9c51-0fd9255897e6.png">

**Comment by LV-Soft** [comment]
You need to provide more information to understand the problem...
For example, what were you doing, what item did you want to use, etc.
The more details the better

It is likely that your problem is because your ped had something in the inventory that you removed from qbcore.shared.items

Try to empty your inventory from the database, set the 'inventory' field to '[]'

**Comment by MonkeyWhisper** [comment]
This isn't for support, not an issue.
