### ISSUE TITLE
lj-inventoy stuck

### ISSUE THREAD

**Issue by Staticdevvv** [loljoshie/lj-inventory#154]
Stuff in inventory gose away when joining back server

**Comment by Boycey280** [comment]
Hello,

I have fixed this issue myself instead of replacing qb-inventory with lj-inventory select the lj-inventory folder in visual sudio and replace lj-inventory with qb-inventory.

once you have done that move lj-inventory folder into resources and delete qb-inventory. Once last thing rename the lj-inventory folder to qb-inventory once you remove the original qb-inventory.

Let me know how it goes
