### ISSUE TITLE
Items disappearing

### ISSUE THREAD

**Issue by dontaythedon** [loljoshie/lj-inventory#158]
Items aren't staying in inventory after relog or reset

getting error on login 

![image](https://user-images.githubusercontent.com/76893439/235205842-15124295-3888-42a0-93f1-d94100269e64.png)

**Comment by ericb160** [comment]
having same problem

**Comment by Boycey280** [comment]
Hello,

I have fixed this issue myself instead of replacing qb-inventory with lj-inventory select the lj-inventory folder in visual sudio and replace lj-inventory with qb-inventory.

once you have done that move lj-inventory folder into resources and delete qb-inventory. Once last thing rename the lj-inventory folder to qb-inventory once you remove the original qb-inventory.

Let me know how it goes

**Comment by ReazCho** [comment]
> Hello,
> 
> I have fixed this issue myself instead of replacing qb-inventory with lj-inventory select the lj-inventory folder in visual sudio and replace lj-inventory with qb-inventory.
> 
> once you have done that move lj-inventory folder into resources and delete qb-inventory. Once last thing rename the lj-inventory folder to qb-inventory once you remove the original qb-inventory.
> 
> Let me know how it goes

for me it dosent work
