### ISSUE TITLE
Inventory is blank

### ISSUE THREAD

**Issue by tonyydung126** [loljoshie/lj-inventory#161]
HI, i have follow all guideline step. But when user load to game. it not have any item on inventory. database is working normally. Many thanks

**Comment by Boycey280** [comment]
Hello,

I have fixed this issue myself instead of replacing qb-inventory with lj-inventory select the lj-inventory folder in visual sudio and replace lj-inventory with qb-inventory.

once you have done that move lj-inventory folder into resources and delete qb-inventory. Once last thing rename the lj-inventory folder to qb-inventory once you remove the original qb-inventory.

Let me know how it goes
